/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NysohButton {
        "label": string;
        "link": string;
        "variant": 'primary' | 'secondary' | 'tertiary';
    }
    interface NysohInput {
        "disabled": boolean;
        "placeholder": string;
        "type": 'button' | 'checkbox' | 'color' | 'date'| 'color'| 'datetime-local'| 'email' | 'file' | 'hidden' | 'image' | 'month' | 'number' | 'password' | 'range' | 'search' | 'submit' | 'tel' | 'text' | 'time' | 'url' | 'week';
        "value": string;
    }
}
declare global {
    interface HTMLNysohButtonElement extends Components.NysohButton, HTMLStencilElement {
    }
    var HTMLNysohButtonElement: {
        prototype: HTMLNysohButtonElement;
        new (): HTMLNysohButtonElement;
    };
    interface HTMLNysohInputElement extends Components.NysohInput, HTMLStencilElement {
    }
    var HTMLNysohInputElement: {
        prototype: HTMLNysohInputElement;
        new (): HTMLNysohInputElement;
    };
    interface HTMLElementTagNameMap {
        "nysoh-button": HTMLNysohButtonElement;
        "nysoh-input": HTMLNysohInputElement;
    }
}
declare namespace LocalJSX {
    interface NysohButton {
        "label"?: string;
        "link"?: string;
        "variant"?: 'primary' | 'secondary' | 'tertiary';
    }
    interface NysohInput {
        "disabled"?: boolean;
        "placeholder"?: string;
        "type"?: 'button' | 'checkbox' | 'color' | 'date'| 'color'| 'datetime-local'| 'email' | 'file' | 'hidden' | 'image' | 'month' | 'number' | 'password' | 'range' | 'search' | 'submit' | 'tel' | 'text' | 'time' | 'url' | 'week';
        "value"?: string;
    }
    interface IntrinsicElements {
        "nysoh-button": NysohButton;
        "nysoh-input": NysohInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nysoh-button": LocalJSX.NysohButton & JSXBase.HTMLAttributes<HTMLNysohButtonElement>;
            "nysoh-input": LocalJSX.NysohInput & JSXBase.HTMLAttributes<HTMLNysohInputElement>;
        }
    }
}
