/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NysohButton {
        "label": string;
        "link": string;
        "variant": 'primary' | 'secondary' | 'tertiary';
    }
}
declare global {
    interface HTMLNysohButtonElement extends Components.NysohButton, HTMLStencilElement {
    }
    var HTMLNysohButtonElement: {
        prototype: HTMLNysohButtonElement;
        new (): HTMLNysohButtonElement;
    };
    interface HTMLElementTagNameMap {
        "nysoh-button": HTMLNysohButtonElement;
    }
}
declare namespace LocalJSX {
    interface NysohButton {
        "label"?: string;
        "link"?: string;
        "variant"?: 'primary' | 'secondary' | 'tertiary';
    }
    interface IntrinsicElements {
        "nysoh-button": NysohButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nysoh-button": LocalJSX.NysohButton & JSXBase.HTMLAttributes<HTMLNysohButtonElement>;
        }
    }
}
